### ISSUE TITLE
Hyphenation not working in Firefox due to lack of lang attribute of html tag

### ISSUE THREAD

**Issue by ignisf** [typeplate/typeplate.github.io#150]
Hello,

In Firefox the hyphenation only works when the document language is specified.

This should probably be mentioned in the docs, too

**Comment by grayghostvisuals** [comment]
Thanks. Please file this issue on the repo of the project [https://github.com/typeplate/starter-kit/issues](https://github.com/typeplate/starter-kit/issues) as specified in the README.
